### ISSUE TITLE
m1 mac에서의 docker-compose.yml 실행 오류

### ISSUE THREAD

**Issue by kimseonghun** [woowacourse/java-deploy#2]
m1을 사용하는 경우 아래와 같은 에러 발생합니다.

```
matching manifest for linux/arm64/v8 in the manifest list entries
```

이를 해결하기 위해 `docker-compose.yml` 파일에 아래 내용을 추가줘야한다고 하는데요, intel mac에서도 작동하는지 확인 후에 업데이트 해야하지 않을까 싶어요.

```yaml
services:
   local-db:
     image: library/mysql:5.7
     platform: linux/amd64        ## 새로 추가가 필요한 항목
```
